export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const POST_PROFILES = "POST_PROFILES";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
// export const CREATE_PROFILE = CREATE_PROFILE;
